POST http://localhost:3000/file-upload
# Content-type과 바운더리 설정
Content-Type: multipart/form-data; boundary=test-file-upload

--test-file-upload #파일 매개변수 정보시작
Content-Disposition: form-data; name="file"; filename="test.txt"

여기에 텍스트파일의 내용을 넣을 수 있습니다.
< test.txt
--test-file-upload--

###사진업로드
POST http://localhost:3000/file-upload
Content-Type: multipart/form-data; boundary=image-file-upload

--image-file-upload
Content-Disposition: form-data; name="file"; filename="test-image.jpg"
Content-type: image/jpeg

< test-image.jpg
--image-file-upload--
