@server = http://localhost:3000

GET {{{server}}/person}

POST {{{server}}/person}}
Content-Type: application/json
{
  "name": "John Doe",
  "age": 30,
  "email": "john.doe@example.com"
}

GET {{server}}/person/john.doe@example.com

PUT {{server}}/person/john.doe@example.com
Content-Type: application/json
{
  "age": 31
}

DELETE {{server}}/person/john.doe@example.com