POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "andy@example.com",
  "password": "password123",
  "username": "andy"
}

### 로그인

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "andy@example.com",
  "password": "password123"
}

### 로그인2 : LOGIN GUARD

POST http://localhost:3000/auth/login2
Content-Type: application/json

{
  "email": "andy@example.com",
  "password": "password123"
}

### Guard 테스트
GET http://localhost:3000/auth/test-guard